spring.application.name=Halleyx

spring.datasource.url=jdbc:mysql://localhost:3306/Halleyx_db
spring.datasource.username=root
spring.datasource.password=sk@11

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true